# This workflow runs the pre-commit hooks on all files and confirms the docs can be built.
#
# Author: Stefanie Molin

name: Check PR

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  # Check that docs can be built
  docs:
    runs-on: ubuntu-latest
    name: Build docs

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          fetch-depth: 0

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c  # v6.0.0
        with:
          python-version: "3.x"

      - name: Install docs dependencies
        run: |
          python -m pip install . --group docs

      - name: Sphinx build
        run: |
          cd docs
          make html
