# This workflow checks that the CITATION.cff file is valid, if it is included in the PR.
#
# Author: Stefanie Molin

name: Validate CITATION.cff

on:
  pull_request:
    paths:
      - 'CITATION.cff'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # check that the CITATION.cff configuration is valid
  citation:
    runs-on: ubuntu-latest
    name: Validate CITATION.cff
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
        with:
          python-version: "3.x"
      - name: Install cffconvert
        run: pip install cffconvert
      - name: Validate
        run: |
          verdict=$(cffconvert --validate)
          echo $verdict
          if [[ $verdict != "Citation metadata are valid"* ]]; then
            exit 1
          fi
